nix: Ignore poetry.group.dev.dependencies for nowo
Seems like there's a collision in files from `pandas` and `pandas-stubs`
which results in a failure to check the flake:

```
error: collision between
`/nix/store/hmznrdy6zdw52g7hj69nlrkvlrgsxiry-python3.11-pandas-1.5.3/lib/python3.11/site-packages/pandas/_libs/interval.pyi'
and
`/nix/store/4wrijjngdkwmiaa7pkwpy61mbbza4sab-python3.11-pandas-stubs-1.2.0.62/lib/python3.11/site-packages/pandas/_libs/interval.pyi'
```

Since `pandas-stubs` is only used for the type-checker, ignore it until
a more proper solution is in place.